% path to outputTrx.m () outputLabel.m padgrab.m required.
% addpath ~/projects/fromAlice/code ~/projects/JCtrax/misc should be enough

% convertAliceData('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie01_pBDPGAL4U_TrpA_Rig1Plate10BowlA_20110202T105734_fly1_11.mat', 'sharpturn');
% convertAliceData('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie01_pBDPGAL4U_TrpA_Rig1Plate10BowlA_20110202T105734_fly2_08.mat', 'sharpturn');
% convertAliceData('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie02_pBDPGAL4U_TrpA_Rig2Plate14BowlA_20110202T110111_fly1_01.mat', 'sharpturn');
% convertAliceData('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie02_pBDPGAL4U_TrpA_Rig2Plate14BowlA_20110202T110111_fly2_15.mat', 'sharpturn');
% convertAliceData('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie03_pBDPGAL4U_TrpA_Rig2Plate14BowlB_20110202T110116_fly1_12.mat', 'sharpturn');
% convertAliceData('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie03_pBDPGAL4U_TrpA_Rig2Plate14BowlB_20110202T110116_fly2_03.mat', 'sharpturn');
% convertAliceData('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie07_GMR_14G03_AE_01_TrpA_Rig2Plate14BowlA_20110202T102516_fly2_17.mat', 'sharpturn');
% convertAliceData('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie08_GMR_14H07_AE_01_TrpA_Rig1Plate10BowlB_20110202T084231_fly1_09.mat', 'sharpturn');
% convertAliceData('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie09_GMR_16E02_AE_01_TrpA_Rig1Plate10BowlC_20110202T140143_fly1_09.mat', 'sharpturn');


% convertAliceData2('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie01_pBDPGAL4U_TrpA_Rig1Plate10BowlA_20110202T105734_fly1_11.mat', '~/projects/larva/dev/fly_data.sharpTurns/Params/SharpturnSVMFeatureParams.txt');
% convertAliceData2('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie01_pBDPGAL4U_TrpA_Rig1Plate10BowlA_20110202T105734_fly2_08.mat', '~/projects/larva/dev/fly_data.sharpTurns/Params/SharpturnSVMFeatureParams.txt');
% convertAliceData2('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie02_pBDPGAL4U_TrpA_Rig2Plate14BowlA_20110202T110111_fly1_01.mat', '~/projects/larva/dev/fly_data.sharpTurns/Params/SharpturnSVMFeatureParams.txt');
% convertAliceData2('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie02_pBDPGAL4U_TrpA_Rig2Plate14BowlA_20110202T110111_fly2_15.mat', '~/projects/larva/dev/fly_data.sharpTurns/Params/SharpturnSVMFeatureParams.txt');
% convertAliceData2('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie03_pBDPGAL4U_TrpA_Rig2Plate14BowlB_20110202T110116_fly1_12.mat', '~/projects/larva/dev/fly_data.sharpTurns/Params/SharpturnSVMFeatureParams.txt');
% convertAliceData2('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie03_pBDPGAL4U_TrpA_Rig2Plate14BowlB_20110202T110116_fly2_03.mat', '~/projects/larva/dev/fly_data.sharpTurns/Params/SharpturnSVMFeatureParams.txt');
% convertAliceData2('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie07_GMR_14G03_AE_01_TrpA_Rig2Plate14BowlA_20110202T102516_fly2_17.mat', '~/projects/larva/dev/fly_data.sharpTurns/Params/SharpturnSVMFeatureParams.txt');
% convertAliceData2('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie08_GMR_14H07_AE_01_TrpA_Rig1Plate10BowlB_20110202T084231_fly1_09.mat', '~/projects/larva/dev/fly_data.sharpTurns/Params/SharpturnSVMFeatureParams.txt');
% convertAliceData2('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie09_GMR_16E02_AE_01_TrpA_Rig1Plate10BowlC_20110202T140143_fly1_09.mat', '~/projects/larva/dev/fly_data.sharpTurns/Params/SharpturnSVMFeatureParams.txt');

convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie01_pBDPGAL4U_TrpA_Rig1Plate10BowlA_20110202T105734_fly1_11.mat', '~/projects/larva/dev/fly_data.sharpTurns/Params/SharpturnSVMFeatureParams.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie01_pBDPGAL4U_TrpA_Rig1Plate10BowlA_20110202T105734_fly2_08.mat', '~/projects/larva/dev/fly_data.sharpTurns/Params/SharpturnSVMFeatureParams.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie02_pBDPGAL4U_TrpA_Rig2Plate14BowlA_20110202T110111_fly1_01.mat', '~/projects/larva/dev/fly_data.sharpTurns/Params/SharpturnSVMFeatureParams.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie02_pBDPGAL4U_TrpA_Rig2Plate14BowlA_20110202T110111_fly2_15.mat', '~/projects/larva/dev/fly_data.sharpTurns/Params/SharpturnSVMFeatureParams.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie03_pBDPGAL4U_TrpA_Rig2Plate14BowlB_20110202T110116_fly1_12.mat', '~/projects/larva/dev/fly_data.sharpTurns/Params/SharpturnSVMFeatureParams.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie03_pBDPGAL4U_TrpA_Rig2Plate14BowlB_20110202T110116_fly2_03.mat', '~/projects/larva/dev/fly_data.sharpTurns/Params/SharpturnSVMFeatureParams.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie07_GMR_14G03_AE_01_TrpA_Rig2Plate14BowlA_20110202T102516_fly2_17.mat', '~/projects/larva/dev/fly_data.sharpTurns/Params/SharpturnSVMFeatureParams.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie08_GMR_14H07_AE_01_TrpA_Rig1Plate10BowlB_20110202T084231_fly1_09.mat', '~/projects/larva/dev/fly_data.sharpTurns/Params/SharpturnSVMFeatureParams.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie09_GMR_16E02_AE_01_TrpA_Rig1Plate10BowlC_20110202T140143_fly1_09.mat', '~/projects/larva/dev/fly_data.sharpTurns/Params/SharpturnSVMFeatureParams.txt');

convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie01_pBDPGAL4U_TrpA_Rig1Plate10BowlA_20110202T105734_fly1_11.mat', '~/projects/larva/dev/fly_data.sharpTurns.absdtheta/Params/SharpturnSVMFeatureParams.absdtheta.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie01_pBDPGAL4U_TrpA_Rig1Plate10BowlA_20110202T105734_fly2_08.mat', '~/projects/larva/dev/fly_data.sharpTurns.absdtheta/Params/SharpturnSVMFeatureParams.absdtheta.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie02_pBDPGAL4U_TrpA_Rig2Plate14BowlA_20110202T110111_fly1_01.mat', '~/projects/larva/dev/fly_data.sharpTurns.absdtheta/Params/SharpturnSVMFeatureParams.absdtheta.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie02_pBDPGAL4U_TrpA_Rig2Plate14BowlA_20110202T110111_fly2_15.mat', '~/projects/larva/dev/fly_data.sharpTurns.absdtheta/Params/SharpturnSVMFeatureParams.absdtheta.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie03_pBDPGAL4U_TrpA_Rig2Plate14BowlB_20110202T110116_fly1_12.mat', '~/projects/larva/dev/fly_data.sharpTurns.absdtheta/Params/SharpturnSVMFeatureParams.absdtheta.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie03_pBDPGAL4U_TrpA_Rig2Plate14BowlB_20110202T110116_fly2_03.mat', '~/projects/larva/dev/fly_data.sharpTurns.absdtheta/Params/SharpturnSVMFeatureParams.absdtheta.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie07_GMR_14G03_AE_01_TrpA_Rig2Plate14BowlA_20110202T102516_fly2_17.mat', '~/projects/larva/dev/fly_data.sharpTurns.absdtheta/Params/SharpturnSVMFeatureParams.absdtheta.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie08_GMR_14H07_AE_01_TrpA_Rig1Plate10BowlB_20110202T084231_fly1_09.mat', '~/projects/larva/dev/fly_data.sharpTurns.absdtheta/Params/SharpturnSVMFeatureParams.absdtheta.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie09_GMR_16E02_AE_01_TrpA_Rig1Plate10BowlC_20110202T140143_fly1_09.mat', '~/projects/larva/dev/fly_data.sharpTurns.absdtheta/Params/SharpturnSVMFeatureParams.absdtheta.txt');

convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie01_pBDPGAL4U_TrpA_Rig1Plate10BowlA_20110202T105734_fly1_11.mat', '~/projects/larva/dev/fly_data.sharpTurns.theta3/Params/SharpturnSVMFeatureParams.theta3.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie01_pBDPGAL4U_TrpA_Rig1Plate10BowlA_20110202T105734_fly2_08.mat', '~/projects/larva/dev/fly_data.sharpTurns.theta3/Params/SharpturnSVMFeatureParams.theta3.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie02_pBDPGAL4U_TrpA_Rig2Plate14BowlA_20110202T110111_fly1_01.mat', '~/projects/larva/dev/fly_data.sharpTurns.theta3/Params/SharpturnSVMFeatureParams.theta3.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie02_pBDPGAL4U_TrpA_Rig2Plate14BowlA_20110202T110111_fly2_15.mat', '~/projects/larva/dev/fly_data.sharpTurns.theta3/Params/SharpturnSVMFeatureParams.theta3.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie03_pBDPGAL4U_TrpA_Rig2Plate14BowlB_20110202T110116_fly1_12.mat', '~/projects/larva/dev/fly_data.sharpTurns.theta3/Params/SharpturnSVMFeatureParams.theta3.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie03_pBDPGAL4U_TrpA_Rig2Plate14BowlB_20110202T110116_fly2_03.mat', '~/projects/larva/dev/fly_data.sharpTurns.theta3/Params/SharpturnSVMFeatureParams.theta3.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie07_GMR_14G03_AE_01_TrpA_Rig2Plate14BowlA_20110202T102516_fly2_17.mat', '~/projects/larva/dev/fly_data.sharpTurns.theta3/Params/SharpturnSVMFeatureParams.theta3.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie08_GMR_14H07_AE_01_TrpA_Rig1Plate10BowlB_20110202T084231_fly1_09.mat', '~/projects/larva/dev/fly_data.sharpTurns.theta3/Params/SharpturnSVMFeatureParams.theta3.txt');
convertAliceData3('/groups/branson/home/schusterreiterc/projects/fromAlice/labelsSharpTurns/labeledsharpturns_movie09_GMR_16E02_AE_01_TrpA_Rig1Plate10BowlC_20110202T140143_fly1_09.mat', '~/projects/larva/dev/fly_data.sharpTurns.theta3/Params/SharpturnSVMFeatureParams.theta3.txt');


convertAliceData3('U:\projects\fromAlice\labelsSharpTurns\labeledsharpturns_movie01_pBDPGAL4U_TrpA_Rig1Plate10BowlA_20110202T105734_fly1_11.mat', 'C:\Users\schusterreiterc\Documents\projects\Jdetect\larva\fly_data.sharpTurns.absdtheta_velmag\Params\SharpturnSVMFeatureParams.absdtheta_velmag.txt');
convertAliceData3('U:\projects\fromAlice\labelsSharpTurns\labeledsharpturns_movie01_pBDPGAL4U_TrpA_Rig1Plate10BowlA_20110202T105734_fly2_08.mat', 'C:\Users\schusterreiterc\Documents\projects\Jdetect\larva\fly_data.sharpTurns.absdtheta_velmag\Params\SharpturnSVMFeatureParams.absdtheta_velmag.txt');
convertAliceData3('U:\projects\fromAlice\labelsSharpTurns\labeledsharpturns_movie02_pBDPGAL4U_TrpA_Rig2Plate14BowlA_20110202T110111_fly1_01.mat', 'C:\Users\schusterreiterc\Documents\projects\Jdetect\larva\fly_data.sharpTurns.absdtheta_velmag\Params\SharpturnSVMFeatureParams.absdtheta_velmag.txt');
convertAliceData3('U:\projects\fromAlice\labelsSharpTurns\labeledsharpturns_movie02_pBDPGAL4U_TrpA_Rig2Plate14BowlA_20110202T110111_fly2_15.mat', 'C:\Users\schusterreiterc\Documents\projects\Jdetect\larva\fly_data.sharpTurns.absdtheta_velmag\Params\SharpturnSVMFeatureParams.absdtheta_velmag.txt');
convertAliceData3('U:\projects\fromAlice\labelsSharpTurns\labeledsharpturns_movie03_pBDPGAL4U_TrpA_Rig2Plate14BowlB_20110202T110116_fly1_12.mat', 'C:\Users\schusterreiterc\Documents\projects\Jdetect\larva\fly_data.sharpTurns.absdtheta_velmag\Params\SharpturnSVMFeatureParams.absdtheta_velmag.txt');
convertAliceData3('U:\projects\fromAlice\labelsSharpTurns\labeledsharpturns_movie03_pBDPGAL4U_TrpA_Rig2Plate14BowlB_20110202T110116_fly2_03.mat', 'C:\Users\schusterreiterc\Documents\projects\Jdetect\larva\fly_data.sharpTurns.absdtheta_velmag\Params\SharpturnSVMFeatureParams.absdtheta_velmag.txt');
convertAliceData3('U:\projects\fromAlice\labelsSharpTurns\labeledsharpturns_movie07_GMR_14G03_AE_01_TrpA_Rig2Plate14BowlA_20110202T102516_fly2_17.mat', 'C:\Users\schusterreiterc\Documents\projects\Jdetect\larva\fly_data.sharpTurns.absdtheta_velmag\Params\SharpturnSVMFeatureParams.absdtheta_velmag.txt');
convertAliceData3('U:\projects\fromAlice\labelsSharpTurns\labeledsharpturns_movie08_GMR_14H07_AE_01_TrpA_Rig1Plate10BowlB_20110202T084231_fly1_09.mat', 'C:\Users\schusterreiterc\Documents\projects\Jdetect\larva\fly_data.sharpTurns.absdtheta_velmag\Params\SharpturnSVMFeatureParams.absdtheta_velmag.txt');
convertAliceData3('U:\projects\fromAlice\labelsSharpTurns\labeledsharpturns_movie09_GMR_16E02_AE_01_TrpA_Rig1Plate10BowlC_20110202T140143_fly1_09.mat', 'C:\Users\schusterreiterc\Documents\projects\Jdetect\larva\fly_data.sharpTurns.absdtheta_velmag\Params\SharpturnSVMFeatureParams.absdtheta_velmag.txt');

convertAliceData3('U:\projects\fromAlice\labelsSharpTurns\labeledsharpturns_movie01_pBDPGAL4U_TrpA_Rig1Plate10BowlA_20110202T105734_fly1_11.mat', 'C:\Users\schusterreiterc\Documents\projects\Jdetect\larva\fly_data.sharpTurns.absdtheta_velmag.mess_here\Params\SharpturnSVMFeatureParams.absdtheta_velmag.txt');
