function scoresAsInput= ...
  collectScoresAsInput(fileNameList, ...
                       timeStampList, ...
                       scoreBaseNameList)
                        
% Collects the three fields that make up the scoresasinput structure into 
% a structure with proper field names.  1st and 3rd args are column cell
% arrays of strings, 2nd arg is a column array.

scoresAsInput=struct('classifierfile',fileNameList, ...
                     'ts',num2cell(timeStampList), ...
                     'scorefilename',scoreBaseNameList);

end
