function ...
  everythingFileFromOldStyleProjectAndClassifierFiles(...
    everythingFileName, ...
    projectFileName, ...
    classifierFileName)

projectParams=load(projectFileName,'-mat');
if isempty(classifierFileName)
  classifierParams=struct([]);
else
  classifierParams=load(classifierFileName,'-mat');
end
everythingParams= ...
  everythingFromOldStyleProjectAndClassifier(projectParams, ...
                                             classifierParams);  %#ok
save(everythingFileName,'-struct','everythingParams');  

end                                    
