function [featureLexicon,animalType]= ...
  featureLexiconFromFeatureLexiconName(featureLexiconName,varargin)

[featureLexiconNameList, ...
 featureLexiconFileNameList, ...
 featureLexiconAnimalTypeList] = ...
  getFeatureLexiconListsFromXML(varargin{:});
    
indexOfFeatureLexicon= ...
  find(strcmp(featureLexiconName,featureLexiconNameList));
if isempty(indexOfFeatureLexicon)
  error('featureLexiconFromFeatureLexiconName:unknownFeatureLexiconName', ...
        'Unknown feature lexicon name');
end
featureLexiconFileName=...
  featureLexiconFileNameList{indexOfFeatureLexicon};
animalType=...
  featureLexiconAnimalTypeList{indexOfFeatureLexicon};

featureLexicon=ReadXMLParams(featureLexiconFileName);

end
