function labels=getLabelsFromExpDirs(expDirNames,labelFileNameRel)

nExps=length(expDirNames);
labels = ...
  struct('t0s',cell(1,nExps), ...
         't1s',cell(1,nExps), ...
         'names',cell(1,nExps), ...
         'flies',cell(1,nExps), ...
         'off',cell(1,nExps), ...
         'timestamp',cell(1,nExps), ...
         'imp_t0s',cell(1,nExps), ...
         'imp_t1s',cell(1,nExps));
fieldNames=fieldnames(labels);       
for i=1:nExps
  labelFileNameAbs=fullfile(expDirNames{i},labelFileNameRel);
  labelsThisExp=load(labelFileNameAbs,'-mat');
  for j=1:length(fieldNames)
    fieldName=fieldNames{j};
    labels(i).(fieldName)=labelsThisExp.(fieldName);
  end
end

end
