function trx = genTrack(nframes,vsz)

trx = struct('x',repmat(vsz(2)/2,1,nframes),...
  'y',repmat(vsz(1)/2,1,nframes),...
  'theta',repmat(0,1,nframes),...
  'a',repmat(5,1,nframes),...
  'b',repmat(2,1,nframes),...
  'x_mm',repmat(vsz(2)/2,1,nframes),...
  'y_mm',repmat(vsz(1)/2,1,nframes),...
  'theta_mm',repmat(0,1,nframes),...
  'a_mm',repmat(5,1,nframes),...
  'b_mm',repmat(2,1,nframes),...
  'id',0,...
  'moviename','',....
  'annname','',...
  'off',0,...
  'firstframe',1,...
  'nframes',nframes,...
  'endframe',nframes,...
  'timestamps',(1:nframes)/30,...
  'matname',-1,...
  'dt',repmat(1/30,1,nframes),...
  'fps',30,...
  'pxpermm',1);
  
  
  