addpath ../../Jdetect/Jdetect/perframe;
SetUpJAABAPath;

expdir = '/groups/hantman/hantmanlab/Jay/videos/M119_CNO_G6/2nd_T/20140409/M119_20140409_v01';

jabfiles = {
  '/groups/hantman/hantmanlab/Adam/Jabfiles/Liftm119.jab'
  '/groups/hantman/hantmanlab/Adam/Jabfiles/Handopenm119.jab'
  '/groups/hantman/hantmanlab/Adam/Jabfiles/Grabm119.jab'
  '/groups/hantman/hantmanlab/Adam/Jabfiles/Supm119.jab'
  '/groups/hantman/hantmanlab/Adam/Jabfiles/Atmouthm119.jab'
  '/groups/hantman/hantmanlab/Adam/Jabfiles/Chewm119.jab'
};

classifierparamsfile = 'JabFileList_m119_20140606.txt';
fid = fopen(classifierparamsfile,'w');
fprintf(fid,'%s\n',jabfiles{:});
fclose(fid);

behaviorname_dict = {
  'Atmouthm119','At mouth'
  'Chewm119','Chew'
  'Grabm119','Grab'
  'Handopenm119','Hand open'
  'Liftm119','Lift'
  'Supm119','Supinate'
  };

behavior_colors = lines(numel(jabfiles));

framestarts = 201;
nframesperseg = 800;
targets = 1;

[~,experiment_name] = fileparts(expdir);
aviname = ['JAABAResultsMovie_',experiment_name,'.avi'];

[readframe,nframes,fid,headerinfo] = get_readframe_fcn(fullfile(expdir,'movie_comb.avi'));
fixedaxis = [1,headerinfo.nc,1,headerinfo.nr];

figpos = [50 50 1500 668];

textcolor = [1,1,1];

fps = 30;

printnone = false;

MakeJAABAResultsMovie(expdir,classifierparamsfile,...
  'framestarts',framestarts,'nframesperseg',nframesperseg,...
  'targets',targets,...
  'behaviorname_dict',behaviorname_dict,...
  'behavior_colors',behavior_colors,...
  'aviname',aviname,...
  'behaviorweight',1,...
  'fixedaxis',fixedaxis,...
  'figpos',figpos,...
  'textcolor',textcolor,...
  'isstjaaba',true,...
  'fps',fps,...
  'printnone',printnone);
% 
% [framestarts,nframesperseg,fracstarts,fracperseg,targets,hfig,...
%   pxwidthradius,pxheightradius,awidthradius,aheightradius,frac_bottom,...
%   trx_linewidth,target_linewidth,...
%   behavior_colors,behavior_cm,...
%   border_bottom,border_middle,bar_width,...
%   trx_rad,score_norm_prctile,...
%   pxborder,aborder,...
%   trxcolor,...
%   figpos,...
%   barbackcolor,...
%   behaviorweight,...
%   textcolor,fontsize,...
%   pxback,aback,...
%   printnone,...
%   mintrajlength,...
%   nintervals,...
%   useVideoWriter,...
%   avifileTempDataFile,aviname,fps,...
%   usemencoder,titlepagetext,...
%   titlepausetime,...
%   behaviorname_dict,...
%   behaviororder,...
%   textprefix,...
%   textsuffix,...
%   fixedaxis,...
%   animaltype,...
%   headmarksize,...
%   bottomtextfontsize] = ...
%   myparse(varargin,'framestarts',[],'nframesperseg',[],...
%   'fracstarts',[],'fracperseg',1/60,...
%   'targets',[],...
%   'hfig',1,...
%   'pxwidthradius',[],...
%   'pxheightradius',[],...
%   'awidthradius',3,...
%   'aheightradius',3,...
%   'frac_bottom',frac_bottom,...
%   'trx_linewidth',trx_linewidth,...
%   'target_linewidth',target_linewidth,...
%   'behavior_colors',zeros(0,3),...
%   'behavior_cm',@(x) jet(x)*.7,...
%   'border_bottom',border_bottom,...
%   'border_middle',border_middle,...
%   'bar_width',bar_width,...
%   'trx_rad',trx_rad,...
%   'score_norm_prctile',80,...
%   'pxborder',pxborder,...
%   'aborder',aborder,...
%   'trxcolor',trxcolor,...
%   'figpos',figpos,...
%   'barbackcolor',barbackcolor,...
%   'behaviorweight',[],...
%   'textcolor',textcolor,...
%   'fontsize',fontsize,...
%   'pxback',[],...
%   'aback',aback,...
%   'printnone',printnone,...
%   'mintrajlength',mintrajlength,...
%   'nintervals',nintervals,...
%   'useVideoWriter',useVideoWriter,...
%   'avifileTempDataFile','',...
%   'aviname',aviname,...
%   'fps',fps,...
%   'usemencoder',usemencoder,...
%   'titlepagetext',{},...
%   'titlepausetime',2,...
%   'behaviorname_dict',behaviorname_dict,...
%   'behaviororder',{},...
%   'textprefix','',...
%   'textsuffix','',...
%   'fixedaxis',[],...
%   'animaltype',animaltype,...
%   'headmarksize',headmarksize,...
%   'bottomtextfontsize',bottomtextfontsize);