function [success,msg] = Convert2JAABAWrapper(InputDataType,varargin)

[inmoviefile,...
  expdir,moviefilestr,trxfilestr,perframedirstr,...
  arenatype,arenacenterx,arenacentery,...
  arenaradius,arenawidth,arenaheight,...
  pxpermm,fps,overridefps,...
  dosoftlink,leftovers] = myparse_nocheck(varargin,...
  'inmoviefile','',...
  'expdir','','moviefilestr','movie.ufmf','trxfilestr','trx.mat','perframedirstr','perframe',...
  'arenatype','None','arenacenterx',0,'arenacentery',0,...
  'arenaradius',123,'arenawidth',123,'arenaheight',123,...
  'pxpermm',1,'fps',30,...
  'overridefps',false,...
  'dosoftlink',false);

switch InputDataType,
  case 'Ctrax',
    [success,msg] = ConvertCtrax2JAABA(...
      'inmoviefile',inmoviefile,...
      leftovers{:},...
      'expdir',expdir,...
      'moviefilestr',moviefilestr,...
      'trxfilestr',trxfilestr,...
      'perframedirstr',perframedirstr,...
      'overridefps',overridefps,...
      'dosoftlink',dosoftlink,...
      'fps',fps,...
      'pxpermm',pxpermm,...
      'arenatype',arenatype,...
      'arenacenterx',arenacenterx,...
      'arenacentery',arenacentery,...
      'arenaradius',arenaradius,...
      'arenawidth',arenawidth,...
      'arenaheight',arenaheight);
  case 'LarvaeRiveraAlba',
    [success,msg] = ConvertLarvaeRiveraAlba2JAABA(...
      'inmoviefile',inmoviefile,...
      leftovers{:},...
      'expdir',expdir,...
      'moviefilestr',moviefilestr,...
      'trxfilestr',trxfilestr,...
      'perframedirstr',perframedirstr,...
      'overridefps',overridefps,...
      'dosoftlink',dosoftlink);
  case 'MoTr',
    [success,msg] = ConvertMoTr2JAABA(...
      'inmoviefile',inmoviefile,...
      leftovers{:},...
      'expdir',expdir,...
      'moviefilestr',moviefilestr,...
      'trxfilestr',trxfilestr,...
      'perframedirstr',perframedirstr,...
      'overridefps',overridefps,...
      'dosoftlink',dosoftlink,...
      'fps',fps,...
      'pxpermm',pxpermm,...
      'arenatype',arenatype,...
      'arenacenterx',arenacenterx,...
      'arenacentery',arenacentery,...
      'arenaradius',arenaradius,...
      'arenawidth',arenawidth,...
      'arenaheight',arenaheight);
    % TODO: sex and frameinterval
  case 'Qtrax',
    [success,msg] = ConvertQtrax2JAABA(...
      'inmoviefile',inmoviefile,...
      leftovers{:},...
      'expdir',expdir,...
      'moviefilestr',moviefilestr,...
      'trxfilestr',trxfilestr,...
      'perframedirstr',perframedirstr,...
      'overridefps',overridefps,...
      'dosoftlink',dosoftlink,...
      'fps',fps,...
      'arenatype',arenatype,...
      'arenacenterx',arenacenterx,...
      'arenacentery',arenacentery,...
      'arenaradius',arenaradius,...
      'arenawidth',arenawidth,...
      'arenaheight',arenaheight);
    % TODO: dosavecadabrafeats
  case 'MAGATAnalyzer',
    [success,msg] = ConvertMAGATAnalyzer2JAABA(...
      'inmoviefile',inmoviefile,...
      leftovers{:},...
      'expdir',expdir,...
      'moviefilestr',moviefilestr,...
      'trxfilestr',trxfilestr,...
      'perframedirstr',perframedirstr,...
      'overridefps',overridefps,...
      'dosoftlink',dosoftlink,...
      'fps',fps,...
      'pxpermm',pxpermm,...
      'arenatype',arenatype,...
      'arenacenterx',arenacenterx,...
      'arenacentery',arenacentery,...
      'arenaradius',arenaradius,...
      'arenawidth',arenawidth,...
      'arenaheight',arenaheight);
  case 'MWT',
    [success,msg] = ConvertMWT2JAABA(...
      'inmoviefile',inmoviefile,...
      leftovers{:},...
      'expdir',expdir,...
      'moviefilestr',moviefilestr,...
      'trxfilestr',trxfilestr,...
      'perframedirstr',perframedirstr,...
      'overridefps',overridefps,...
      'dosoftlink',dosoftlink,...
      'fps',fps,...
      'pxpermm',pxpermm,...
      'arenatype',arenatype,...
      'arenacenterx',arenacenterx,...
      'arenacentery',arenacentery,...
      'arenaradius',arenaradius,...
      'arenawidth',arenawidth,...
      'arenaheight',arenaheight);
  otherwise
    success = false;
    msg = sprintf('Unknown data type %s',InputDataType);
end