%% script for making plots used to demonstrate accuracy of detectors

%% set up path

addpath ../perframe;
addpath ../perframe/compute_perframe_features;
addpath ../misc;
addpath ../filehandling;
addpath C:\Code\Ctrax\trunk\matlab\netlab;
outfigdir = 'C:/Code/Jdetect/figures/AccuracyOut';
if ~exist(outfigdir,'dir'),
  mkdir(outfigdir);
end


%% global parameters

% sample frames
annfilestr = 'movie.ufmf.ann';
colorpos = [.7,0,0];
colorneg = [0,0,.7];
border = 16;
bg_thresh = 10/255;
wmah = .5;
frac_a_back = 1;
dist_epsilon = .1;
figpos_example = [100 400 1800 650];

TOUCH = 1;
CRABWALK = 2;
BACKUP = 3;
CHASE = 4;
WINGGROOMING = 5;
JUMP = 6;


%% TOUCH parameters

behavior = 'Touch';
scoresfilestr = 'scoresTouch.mat';
rootdatadir = 'C:/Data/JAABA/groundtruth_pBDPGAL4U_data';
experiment_name = 'pBDPGAL4U_TrpA_Rig2Plate17BowlC_20110811T133805';
mainfly = 3;
otherflies = 18;
ts = [13879,13882,13888,13892,13894,13899];
ts_overlay = [13875,13882,13888,13899];

%% TOUCH draw example frames

PlotSampleFramesWrapper(behavior,rootdatadir,experiment_name,...
  scoresfilestr,mainfly,otherflies,ts,ts_overlay,...
  'outfigdir',outfigdir,...
  'annfilestr',annfilestr,...
  'colorpos',colorpos,...
  'colorneg',colorneg,...
  'border',border,...
  'bg_thresh',bg_thresh,...
  'wmah',wmah,...
  'frac_a_back',frac_a_back,...
  'dist_epsilon',dist_epsilon,...
  'figpos',figpos_example,...
  'hfig_base',TOUCH*100);

%% CRABWALK

behavior = 'Crabwalk';
scoresfilestr = 'scoresCrabwalk.mat';
rootdatadir = 'C:/Data/JAABA/groundtruth_pBDPGAL4U_data';
experiment_name = 'pBDPGAL4U_TrpA_Rig1Plate10BowlB_20110609T091905';
mainfly = 19;
otherflies = [];
ts = 15383:4:15403;
ts_overlay = 15383:4:15423;
%ts = round(linspace(15370,15407,6));

%% CRABWALK draw example frames

PlotSampleFramesWrapper(behavior,rootdatadir,experiment_name,...
  scoresfilestr,mainfly,otherflies,ts,ts_overlay,...
  'outfigdir',outfigdir,...
  'annfilestr',annfilestr,...
  'colorpos',colorpos,...
  'colorneg',colorneg,...
  'border',border,...
  'bg_thresh',bg_thresh,...
  'wmah',wmah,...
  'frac_a_back',frac_a_back,...
  'dist_epsilon',dist_epsilon,...
  'figpos',figpos_example,...
  'hfig_base',CRABWALK*100);

%% BACKUP

behavior = 'Backup';
scoresfilestr = 'scoresBackup.mat';
rootdatadir = 'C:/Data/JAABA/FlyBowl';
experiment_name = 'pBDPGAL4U_TrpA_Rig1Plate15BowlB_20110922T145928';
mainfly = 1;
otherflies = [];
ts = 12390:4:12406;
ts_overlay = [12390,12398,12406];

%% BACKUP draw example frames

PlotSampleFramesWrapper(behavior,rootdatadir,experiment_name,...
  scoresfilestr,mainfly,otherflies,ts,ts_overlay,...
  'outfigdir',outfigdir,...
  'annfilestr',annfilestr,...
  'colorpos',colorpos,...
  'colorneg',colorneg,...
  'border',border,...
  'bg_thresh',bg_thresh,...
  'wmah',wmah,...
  'frac_a_back',frac_a_back,...
  'dist_epsilon',dist_epsilon,...
  'figpos',figpos_example,...
  'hfig_base',BACKUP*100);


%% CHASE

behavior = 'Chase';
scoresfilestr = 'scoresChasev7.mat';
rootdatadir = 'C:/Data/JAABA/FlyBowl';
experiment_name = 'pBDPGAL4U_TrpA_Rig1Plate15BowlB_20110922T145928';
mainfly = 20;
otherflies = [12];
ts_overlay = [6440,6461,6470,6480,6490];
ts = ts_overlay;

%% CHASE plot example frames

PlotSampleFramesWrapper(behavior,rootdatadir,experiment_name,...
  scoresfilestr,mainfly,otherflies,ts,ts_overlay,...
  'outfigdir',outfigdir,...
  'annfilestr',annfilestr,...
  'colorpos',colorpos,...
  'colorneg',colorneg,...
  'border',border,...
  'bg_thresh',bg_thresh,...
  'wmah',wmah,...
  'frac_a_back',frac_a_back,...
  'dist_epsilon',dist_epsilon,...
  'figpos',figpos_example,...
  'hfig_base',CHASE*100);

%% WINGGROOMING

behavior = 'WingGrooming';
scoresfilestr = 'scoresWingGrooming.mat';
rootdatadir = 'C:/Data/JAABA/FlyBowl';
experiment_name = 'pBDPGAL4U_TrpA_Rig2Plate14BowlD_20110615T164545';
mainfly = 17;
otherflies = [];
%ts = [9962,9963,9964,9965,9966,9967,9968];
%ts = [10179,10185,10186,10187,10188,10189];
ts = 10291:10296;
ts_overlay = ts;
%ts = round(linspace(15370,15407,6));

%% WINGGROOMING plot example frames

PlotSampleFramesWrapper(behavior,rootdatadir,experiment_name,...
  scoresfilestr,mainfly,otherflies,ts,ts_overlay,...
  'outfigdir',outfigdir,...
  'annfilestr',annfilestr,...
  'colorpos',colorpos,...
  'colorneg',colorneg,...
  'border',border,...
  'bg_thresh',bg_thresh,...
  'wmah',wmah,...
  'frac_a_back',frac_a_back,...
  'dist_epsilon',dist_epsilon,...
  'figpos',figpos_example,...
  'hfig_base',WINGGROOMING*100,...
  'doplotellipseoverlay',true);

%% JUMP

behavior = 'Jump';
scoresfilestr = 'scores_Jump.mat';
rootdatadir = 'C:/Data/JAABA/FlyBowl';
experiment_name = 'pBDPGAL4U_TrpA_Rig1Plate15BowlB_20110922T145928';
mainfly = 1;
otherflies = [];
ts = 12390:4:12406;
ts_overlay = ts;
