function [bgcenter1,bgstd1] = compute_bg_model(readframe,nframes,varargin)

[bgalgorithm,bgstartframe,bgendframe,bgnframes,roi,maxmem,verbose] = ...
    myparse(varargin,'bgalgorithm','median',...
            'bgstartframe',1,'bgendframe',nframes,...
            'bgnframes',200,'roi',[],...
            'maxmem',2^20*50,'verbose',1);


if strcmpi(bgalgorithm,'median'),
  [bgcenter1,bgstd1] = compute_bg_med(readframe,nframes,...
                                      'bgstartframe',bgstartframe,...
                                      'bgendframe',bgendframe,...
                                      'bgnframes',bgnframes,...
                                      'roi',roi,...
                                      'maxmem',maxmem);
else
  [bgcenter1,bgstd1] = compute_bg_mean(readframe,nframes,...
                                      'bgstartframe',bgstartframe,...
                                      'bgendframe',bgendframe,...
                                      'bgnframes',bgnframes,...
                                      'roi',roi);
end
